content/2020-12/_index.markdown
content/2020-12/applicator/_index.markdown
content/2020-12/content/_index.markdown
content/2020-12/core/_index.markdown
content/2020-12/format-annotation/_index.markdown
content/2020-12/format-assertion/_index.markdown
content/2020-12/meta-data/_index.markdown
content/2020-12/unevaluated/_index.markdown
content/2020-12/validation/_index.markdown
layouts/_default/section.html

Add author pictures to dialects and vocabularies

---

layouts/_default/section.html

Fix authors figure padding

---

layouts/_default/section.html
layouts/_default/single.html
layouts/partials/keyword-summary.html
layouts/partials/term.html

Link to the official JSON Schema glossary when possible

---

content/2020-12/_index.markdown
layouts/_default/section.html

Add basic BibTex citation instructions for dialects

---

content/2020-12/_index.markdown
content/2020-12/applicator/_index.markdown
content/2020-12/content/_index.markdown
content/2020-12/core/_index.markdown
content/2020-12/format-annotation/_index.markdown
content/2020-12/format-assertion/_index.markdown
content/2020-12/meta-data/_index.markdown
content/2020-12/unevaluated/_index.markdown
content/2020-12/validation/_index.markdown
layouts/_default/section.html

Add authors full names on the website

---

README.markdown

Fix README typo

---

assets/highlight.scss
assets/main.scss
config/_default/config.toml

Improve Hugo syntax highlighting on Markdown files

---

assets/highlight.scss
layouts/_default/section.html

Improve highlighting of vocabulary usage examples

---

content/2020-12/applicator/else.markdown
content/2020-12/applicator/then.markdown

Refer to `if` within `else` and `then` using code blocks

---

layouts/_default/section.html

Clarify instructions on using vocabularies

---

content/2020-12/_index.markdown
layouts/_default/section.html

Link to Bowtie coverage by dialect

---

layouts/_default/section.html
layouts/_default/single.html
layouts/partials/dialect-badge.html

Simplify dialect linking

---

content/2020-12/content/contentMediaType.markdown

Improve summary of `contentMediaType`

---

content/2020-12/validation/type.markdown

This pull request removes repeated data type.

docs: Update type.markdown

---

layouts/partials/navigation.html

I know it's disabled, but it still confused me. It wasn't clear to me that it was disabled. Feel free to merge or close, whichever works.

Remove search bar temporarily

---

assets/main.scss
content/2020-12/validation/type.markdown
layouts/shortcodes/instance-fail.html
layouts/shortcodes/instance-pass.html
layouts/shortcodes/schema.html

See: https://github.com/sourcemeta/learnjsonschema.com/issues/35

Experiment with better docs shortcuts on the `type` keyword

---

content/2020-12/validation/type.markdown
layouts/shortcodes/schema.html

Minor `type` example design fixes

---

assets/main.scss
layouts/shortcodes/instance-fail.html
layouts/shortcodes/instance-pass.html
layouts/shortcodes/schema.html

Support contiguous example blocks

---

content/2020-12/validation/type.markdown

Document array types

---

layouts/partials/vocabulary-badges.html

Fix official badge color

---

DEPENDENCIES
vendor/vendorpull.mask
vendor/vendorpull/pull

Upgrade Vendorpull

---

content/2020-12/validation/enum.markdown

Initial PR.
Juan, please consider providing some suggestions on the type of examples I should cover, specifically in terms of complexity.
_Edit: This PR addresses #86_

add description and examples for `enum` keyword

---

assets/main.scss
config/_default/config.toml
content/2020-12/core/id.markdown
layouts/shortcodes/alert.html
package-lock.json

This PR addresses #47.
It is built upon the changes proposed in #45 and implements the suggested modifications

add description and examples for `$id` keyword

---

content/2020-12/validation/exclusiveMinimum.markdown

add description and examples for `exclusiveMinimum` keyword

---

content/2020-12/validation/exclusiveMaximum.markdown

add description and examples for `exclusiveMaximum` keyword

---

content/2020-12/core/defs.markdown

This PR addresses #50.
Changes requested in #43 have also been addressed.

add description and examples for `$defs` keyword

---

content/2020-12/core/ref.markdown

This PR addresses #49.
Changes requested in #43 have also been addressed.

Keyword `ref`

---

content/2020-12/core/ref.markdown
content/2020-12/validation/dependentRequired.markdown

This PR addresses #96
I wasn't sure how to utilize the patternProperties in a real-world example, so I hardcoded its value. Let me know if you have any suggestions regarding this.

keyword `dependentRequired`

---

content/2020-12/validation/maxItems.markdown

Keyword `maxItems`

---

content/2020-12/validation/uniqueItems.markdown

Keyword `uniqueItems`

---

content/2020-12/validation/maxProperties.markdown

Keyword `maxProperties`

---

content/2020-12/validation/minContains.markdown

Keyword `minContains`

---

content/2020-12/validation/maxContains.markdown
content/2020-12/validation/maxProperties.markdown

Keyword `maxContains`

---

content/2020-12/applicator/properties.markdown
layouts/shortcodes/instance-annotation.html

Keyword `properties`

---

content/2020-12/applicator/patternProperties.markdown
layouts/shortcodes/instance-annotation.html

Keyword `patternProperties`

---

content/2020-12/core/comment.markdown

Keyword `$comment`

---

content/2020-12/applicator/not.markdown

Keyword `not`

---

content/2020-12/applicator/else.markdown

Keyword `else`

---

content/2020-12/applicator/then.markdown

Keyword `then`

---

content/2020-12/format-assertion/format.markdown

Keyword `format` (assertion)

---

content/2020-12/format-annotation/format.markdown

Keyword `format` (annotation)

---

content/2020-12/applicator/dependentSchemas.markdown

Keyword `dependentSchemas`

---

content/2020-12/applicator/prefixItems.markdown

Keyword `prefixItems`

---

content/2020-12/applicator/items.markdown

Keyword `items`

---

content/2020-12/applicator/if.markdown

Keyword `if`

---

content/2020-12/applicator/anyOf.markdown

Keyword `anyOf`

---

content/2020-12/applicator/oneOf.markdown

Keyword `oneOf`

---

content/2020-12/content/contentEncoding.markdown
layouts/shortcodes/instance-annotation.html

Keyword `contentEncoding`

---

content/2020-12/content/contentMediaType.markdown
layouts/shortcodes/instance-annotation.html

Keyword `contentMediaType`

---

content/2020-12/content/contentSchema.markdown
layouts/shortcodes/instance-annotation.html

Keyword `contentSchema`

---

content/2020-12/_index.markdown

Thanks @jviotti and @AgniveshChaubey for this awesome resource!

fix bowtie website link

---

assets/main.js
assets/main.scss
layouts/_default/section.html
layouts/_default/single.html
layouts/partials/breadcrumb.html
layouts/partials/sidebar.html
vendor/bootstrap.mask
vendor/bootstrap/js/src/dropdown.js

Features added: dropdown on hover
Which redirects to syntax http://base.com/{selected_dialect}

Adding dropdown,

---

assets/main.scss

Revise and cleanup `main.scss`

---

layouts/partials/dialect-badge.html

Don't use custom background colors on dialect badges

---

assets/main.scss
layouts/partials/breadcrumb.html
layouts/partials/navigation.html

Revise the navigation bar

---

layouts/_default/section.html

Clarify that author links are external

---

layouts/_default/section.html

Tweak "using a vocabulary" prose

---

content/2020-12/unevaluated/unevaluatedItems.markdown
content/2020-12/unevaluated/unevaluatedProperties.markdown

Fix interdependencies from the Unevaluated vocabulary

---

layouts/_default/single.html

Show "Affected By" for all keywords

---

content/2020-12/core/dynamicRef.markdown
content/2020-12/core/ref.markdown

Clarify that `$id` affects references

---

content/2020-12/applicator/additionalProperties.markdown
content/2020-12/applicator/contains.markdown
content/2020-12/applicator/items.markdown
content/2020-12/applicator/patternProperties.markdown
content/2020-12/applicator/prefixItems.markdown
content/2020-12/applicator/properties.markdown
content/2020-12/content/contentEncoding.markdown
content/2020-12/content/contentMediaType.markdown
content/2020-12/content/contentSchema.markdown
content/2020-12/format-annotation/format.markdown
content/2020-12/format-assertion/format.markdown
content/2020-12/meta-data/default.markdown
content/2020-12/meta-data/deprecated.markdown
content/2020-12/meta-data/description.markdown
content/2020-12/meta-data/examples.markdown
content/2020-12/meta-data/readOnly.markdown
content/2020-12/meta-data/title.markdown
content/2020-12/meta-data/writeOnly.markdown
content/2020-12/unevaluated/unevaluatedItems.markdown
content/2020-12/unevaluated/unevaluatedProperties.markdown
layouts/_default/single.html

Elevate annotation descriptions and types to the reference tables

---

content/2020-12/applicator/else.markdown
content/2020-12/applicator/then.markdown
content/2020-12/validation/maxContains.markdown
content/2020-12/validation/minContains.markdown

Fixes: https://github.com/Intelligence-AI/learnjsonschema.com/issues/175

Fix top-level keyword links

---

content/2020-12/applicator/additionalProperties.markdown
content/2020-12/applicator/if.markdown
content/2020-12/applicator/items.markdown
content/2020-12/applicator/patternProperties.markdown
content/2020-12/applicator/prefixItems.markdown
content/2020-12/applicator/properties.markdown
content/2020-12/content/contentMediaType.markdown
content/2020-12/core/anchor.markdown
content/2020-12/core/dynamicAnchor.markdown
content/2020-12/core/id.markdown
content/2020-12/validation/maxContains.markdown
content/2020-12/validation/minContains.markdown
layouts/_default/single.html

Fixes: https://github.com/Intelligence-AI/learnjsonschema.com/issues/183

Add an "Affects" entry to the keyword tables

---

layouts/_default/single.html

Capitalize "Also See" like other table headings

---

content/2020-12/applicator/items.markdown

Fix link to `prefixItems` in `items` description

---

layouts/partials/help.html

Update GitHub Discussions link on the help alert hint

---

assets/main.scss
content/2020-12/core/ref.markdown
layouts/shortcodes/common-pitfall.html
layouts/shortcodes/instance-annotation.html

The idea is to have a set of richer alert types that provide a visual
language to the user.

Introduce a "Common Pitfall" re-usable shortcode

---

content/2020-12/core/ref.markdown
layouts/shortcodes/alert.html
layouts/shortcodes/common-pitfall.html
layouts/shortcodes/learning-more.html

Introduce an alert shortcode for digging deeper

---

assets/main.scss

Improve the design of the alerts

---

assets/main.scss
content/2020-12/core/schema.markdown
layouts/shortcodes/best-practice.html
layouts/shortcodes/instance-pass.html

Implement an alert type for conveying best practices

---

layouts/partials/help.html

For consistency with other alerts

Avoid a drop shadow on the help alert

---

assets/main.scss
layouts/partials/sidebar.html

Fixes: https://github.com/Intelligence-AI/learnjsonschema.com/issues/194

Fix sidebar vertical overflow

---

layouts/_default/section.html

Fixes: https://github.com/Intelligence-AI/learnjsonschema.com/issues/177

Unify vocabulary usage alerts

---

layouts/partials/vocabulary-badges.html

Don't set custom colors on vocabulary badges

---

assets/main.scss

Fix borders on book promotional alert

---

layouts/partials/sidebar.html

Make sidebar look good on dark mode

---

layouts/partials/footer.html

Make footer look good on a dark theme

---

assets/main.scss
layouts/_default/section.html
layouts/_default/single.html

Make keyword tables look good on dark mode

---

layouts/_default/baseof.html

Remove explicit background color in `body`

---

assets/main.scss
layouts/shortcodes/instance-annotation.html
layouts/shortcodes/instance-fail.html
layouts/shortcodes/instance-pass.html
layouts/shortcodes/schema.html

Make snippet background colors look good on dark mode

---

assets/highlight.scss

Correctly highlight code in dark mode

---

assets/main.scss

Fixes: https://github.com/Intelligence-AI/learnjsonschema.com/issues/1

Enable switching themes based on the browser settings

---

content/2020-12/content/contentEncoding.markdown
content/2020-12/content/contentMediaType.markdown
content/2020-12/core/dynamicRef.markdown
content/2020-12/core/id.markdown
content/2020-12/core/ref.markdown
content/2020-12/core/schema.markdown

Add a space before "RFC" in all cases

---

layouts/_default/baseof.html

Pass CSS over the `minify` Hugo pipe

---

layouts/partials/footer.html

Set a width for the footer logo

---

layouts/_default/section.html

Address various Lighthouse accessibility issues

---

layouts/_default/baseof.html

Set a correct canonical URL

---

assets/main.scss

Use Bootstrap's default blue primary color

---

layouts/shortcodes/instance-annotation.html
layouts/shortcodes/instance-fail.html
layouts/shortcodes/instance-pass.html
layouts/shortcodes/schema.html

Improve design of code blocks

---

content/2020-12/applicator/additionalProperties.markdown
content/2020-12/applicator/contains.markdown
content/2020-12/applicator/if.markdown
content/2020-12/applicator/items.markdown
content/2020-12/applicator/patternProperties.markdown
content/2020-12/applicator/prefixItems.markdown
content/2020-12/applicator/properties.markdown
content/2020-12/content/contentEncoding.markdown
content/2020-12/content/contentMediaType.markdown
content/2020-12/content/contentSchema.markdown
content/2020-12/format-annotation/format.markdown
content/2020-12/format-assertion/format.markdown
content/2020-12/meta-data/default.markdown
content/2020-12/meta-data/deprecated.markdown
content/2020-12/meta-data/description.markdown
content/2020-12/meta-data/examples.markdown
content/2020-12/meta-data/readOnly.markdown
content/2020-12/meta-data/title.markdown
content/2020-12/meta-data/writeOnly.markdown
content/2020-12/unevaluated/unevaluatedItems.markdown
content/2020-12/unevaluated/unevaluatedProperties.markdown

Make annotations more concise

---

.github/workflows/website-build.yml

Make CI work on fork PRs

---

assets/main.js
assets/main.scss
layouts/_default/baseof.html
layouts/shortcodes/schema.html

Fixes #171 
https://github.com/Intelligence-AI/learnjsonschema.com/assets/68469605/66af2761-218f-4ff5-8808-29e6ac678096

Copy to Clipboard Button

---

assets/main.scss

Fix first line of code snippets being hidden

---

.ackrc

Revise `.ackrc`

---

layouts/_default/single.html

Just as a safety check for the future

Assert that a keyword cannot be changed by its own dialect

---

assets/main.scss
layouts/partials/navigation.html

See: https://github.com/Intelligence-AI/jsonschema

Promote our new JSON Schema CLI

---

content/2020-12/_index.markdown
layouts/_default/section.html

Link every dialect to its release notes

---

layouts/partials/sidebar.html

Fix sidebar to show only vocabularies from the selected dialect

---

layouts/_default/section.html

Fix spacing issues on dialect page

---

content/2020-12/applicator/contains.markdown
content/2020-12/applicator/items.markdown

Fix `changed_in` for `contains` and `items` in 2020-12

---

README.markdown

Showcase contributors on the README

---

assets/main.js
assets/main.scss
layouts/partials/sidebar.html

@jviotti I have created the new branch for grouping alphabetical ordering to avoid conflicts. You can check on this once.
Re-opening this https://github.com/Intelligence-AI/learnjsonschema.com/pull/233 PR

Extend the sidebar to see keywords by either vocabulary or alphabetically

---

LICENSE
README.markdown
config/_default/config.toml
layouts/partials/navigation.html

Revise website links and ownership

---

content/2019-09/validation/type.markdown
content/2020-12/validation/type.markdown
content/draft7/validation/type.markdown

Document that `type` changed in Draft 6

---

layouts/partials/navigation.html

Promote new open-source schema registry

---

content/draft3/core/disallow.markdown
content/draft3/core/type.markdown

Fix `type` and `disallow` documentation for Draft 3

---

content/2020-12/validation/type.markdown

Improve documentation for the `type` keyword

---

.github/workflows/website-build.yml
.github/workflows/website-deploy.yml
Dockerfile
Makefile

Build the site on CI using Docker

---

DEPENDENCIES
vendor/vendorpull/LICENSE
vendor/vendorpull/pull
vendor/vendorpull/upgrade

Upgrade `vendorpull` to `1dcbac42809cf87cb5b045106b863e17ad84ba02`

---

content/2019-09/applicator/allOf.markdown
content/draft4/validation/allOf.markdown
content/draft6/validation/allOf.markdown
content/draft7/validation/allOf.markdown

Document `allOf` for previous dialects
